## The api URL of your pocketbase collection, in case you want to track job listings and build listeners for social media integration.
pocketbase-url: "http://127.0.0.1:8090/api/collections/collectionIdOrName/records"
## The authorization for your pocketbase collection.
pocketbase-auth-url: "http://127.0.0.1:8090/api/admins/auth-with-password"
pocketbase-email: ""
pocketbase-password: ""

## This list adds the option to spoof the IP's of specific users. The spoofing only happens internally within the BungeeUserManager database, and it is not passed on to the backend server or any other bungee feature.
ip-spoofing:
  - 00000000-0000-1000-8000-000000000000|255.255.255.255
  - 255.255.255.255|255.255.255.255